apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentd.databaseSecretName" . }}
  labels:
    {{- include "agentd.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ include "agentd.databaseDSN" . | quote }}
  {{- if and (not .Values.database.dsn) .Values.database.mysql.enabled }}
  database: {{ .Values.database.mysql.auth.database | quote }}
  username: {{ .Values.database.mysql.auth.username | quote }}
  password: {{ .Values.database.mysql.auth.password | quote }}
  root-password: {{ .Values.database.mysql.auth.rootPassword | quote }}
  {{- end }}
